version: "3"

services:

  dagit:
    build:
      context: ./skyeng
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - skyeng/.env
    command: "dagit -w workspace.yaml -h 0.0.0.0 -p 3000"
    depends_on:
      - postgres-metadata
    restart: always
    networks:
      - sky_network

  daemon:
    build:
      context: ./skyeng
      dockerfile: Dockerfile
    env_file:
      - skyeng/.env
    command: "dagster-daemon run -w workspace.yaml"
    depends_on:
      - postgres-metadata
    restart: always
    networks:
      - sky_network

  postgres-metadata:
    image: postgres:13
    environment:
      POSTGRES_HOST: 0.0.0.0
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      retries: 5
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-metadata:/var/lib/postgresql/data
    networks:
      - sky_network

networks:
  sky_network: