services:

  c3d3-dagster-dagit:
    build:
      context: ./c3d3
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - c3d3/.env
    command: "dagit -w workspace.yaml -h 0.0.0.0 -p 3000"
    depends_on:
      - c3d3-postgres
    restart: always

  c3d3-dagster-daemon:
    build:
      context: ./c3d3
      dockerfile: Dockerfile
    env_file:
      - c3d3/.env
    command: "dagster-daemon run -w workspace.yaml"
    depends_on:
      - c3d3-postgres
    restart: always

  c3d3-dagster-postgres:
    image: postgres:13
    environment:
      POSTGRES_HOST: c3d3-dagster-postgres
      POSTGRES_USER: c3d3-dagster-postgres
      POSTGRES_PASSWORD: c3d3-dagster-postgres
      POSTGRES_DB: c3d3-dagster-postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "c3d3-dagster-postgres" ]
      interval: 5s
      retries: 5
    restart: always

volumes:
  c3d3-postgres: